export const TOGGLE_PAGE_MODE = "TOGGLE_PAGE_MODE";
export const TOGGLE_HOME_DRAWER = "TOGGLE_HOME_DRAWER";
export const TOGGLE_COURSE_DRAWER = "TOGGLE_COURSE_DRAWER";
export const OPEN_HOME_DRAWER_SUB_MENU = "OPEN_HOME_DRAWER_SUB_MENU";
export const CLOSE_HOME_DRAWER_SUB_MENU = "CLOSE_HOME_DRAWER_SUB_MENU";
export const SET_GO_BACK_NAV_BAR = "SET_GO_BACK_NAV_BAR";
export const SET_HEADER_TITLE = "SET_HEADER_TITLE";
