export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const RESET_AUTH_PENDING = "RESET_AUTH_PENDING";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
