export const GET_ACCOUNT_INFORMATION = "GET_ACCOUNT_INFORMATION";
export const GET_COURSES_WITH_FILTER = "GET_COURSES_WITH_FILTER";
export const RESET_ERROR = "RESET_ERROR";
export const CLEAR_LESSON_DATA = "CLEAR_LESSON_DATA";
export const GET_ALL_TEACHER = "GET_ALL_TEACHER";
